call plug#begin()
Plug 'junegunn/vim-plug'
Plug 'vimwiki/vimwiki'
Plug 'morhetz/gruvbox'
Plug 'yegappan/mru'
call plug#end()

" Traktuj polskie znaki diakrytyczne jak czêœci s³owa
if &encoding == "cp1250"
	set iskeyword+=185,230,234,179,241,243,156,159,191,165,198,202,163
	set iskeyword+=209,211,140,143,175
endif

syntax on

" Rozdzielaj zdania dwoma spacjami
set cpoptions+=J

" Szybkie wychodzenie z trybu wstawiania
inoremap jj <Esc>

" Skrót do wklejania aktualnej daty w trybie NORMAL i INSERT
nmap <F5> "=strftime("%F")<CR>P
imap <F5> <C-R>=strftime("%F")<CR>
" Otwórz aktywny bufor w kodowaniu UTF-8
nmap <F8> :e ++enc=utf8<CR>

" Skocz do nastêpnego <++> w tekœcie i wejdŸ do INSERT
" Mnemonika <C-J>: 'j' od 'jump'
inoremap <C-j> <Esc>:call<Space>search('<++>')<CR>"_cf>
nmap <C-j> i<C-j>

" Zamieñ inicja³ ka¿dego wyrazu na du¿¹ literê (Title Case)
" Szybka aplikacja na obecnym wierszu, w trybie normalnym: Vt
vmap <leader>t :s/\<\(\w\)\(\S*\)/\u\1\L\2/g<CR>

" Wstaw spacjê nie³ami¹c¹ (ang. non-breaking space)
inoremap <c-space> <c-k>NS

" Zamieñ wszystkie ma³e litery na du¿e litery w tekœcie dodanym podczas
" ostatniego u¿ycia trybu wprowadzania INSERT
nmap <leader>u `[v`]<BS>gU

" Wyœwietlaj informacjê o pozycji kursora w pliku
set ruler

" Wyœwietlaj wprowadzane sekwencje klawiszy na dole ekranu.
set showcmd

set listchars=tab:\|\ ,trail:·,nbsp:·
set list

" vimwiki
let wiki = {}
let wiki.name = 'Personal'
let wiki.path = '~/vimwiki/'
let wiki.list_margin = 0

let g:vimwiki_list = [wiki]

language messages en

" Ignoruj adresy URL podczas sprawdzania pisowni
syn match UrlNoSpell '\w\+:\/\/[^[:space:]]\+' contains=@NoSpell

" Wykonaj aktualnie edytowany skrypt (:w nie jest konieczne)
" https://stackoverflow.com/a/39996978/13168106
autocmd FileType python nnoremap <buffer> <F9> :update<bar>term python %<CR>
autocmd FileType ruby nnoremap <buffer> <F9> :update<bar>term ruby %<CR>

autocmd FileType html setlocal shiftwidth=2 tabstop=2
autocmd FileType ruby setlocal expandtab shiftwidth=4 softtabstop=4 tabstop=4
autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4 tabstop=4
autocmd FileType vimwiki
    \ setlocal enc=utf8 nowrap tw=79 expandtab shiftwidth=4 softtabstop=4
autocmd FileType json
    \ setlocal shiftwidth=4 tabstop=4 softtabstop=4 nowrap
